### ISSUE TITLE
Debug Credentials

### ISSUE THREAD

**Issue by padak** [keboola/db-writer-bundle#3]
Ahoj,
mám nastavené credentials v MSSQL Writeru (https://connection.keboola.com/admin/projects/924/writers/wr-db-mssql/powerbi-85/credentials) a když to copy&pastnu do konzole na Syrupu:

[deploy@kbc-vpc-syrup-worker-b-14 ~]$ tsql -H xxxx.database.windows.net -U keboola -P xxxx -p 1433

tak to jede OK. Pokud to pustím v KBC, hodí mi to chybu https://connection.keboola.com/admin/projects/924/jobs/167991090

Na straně Azure jsem povolil 2 IP dvou Syrupů:

![image](https://cloud.githubusercontent.com/assets/1427901/12483361/d5c187ee-c054-11e5-85e5-0a5ea35244df.png)

Padák

**Comment by padak** [comment]
teď jsem to lehce rozjebal... 10 min a bude to zas sedět

**Comment by padak** [comment]
done - jde to testovat

**Comment by MiroCillik** [comment]
Viem kde je problem. Treba nastavit FreeTDS driver na spravnu verziu, rozne typy serverov pouzivaju rozne verzie http://www.freetds.org/userguide/choosingtdsprotocol.htm

Dal som ako default 8.0 a pripadne to mozme spravit konfigurovatelne. 

Myslel som, ze rovnaky problem je aj u toho Nova Leasing, ale tam to nefungovalo so ziadnou verziou :( Takze problem bude asi niekde inde v ich pripade. 

Buildujem novy image v Quay.io, zachvilu to nasadim.

**Comment by padak** [comment]
hustě, díky!


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek


2016-01-21 16:53 GMT+01:00 Miroslav Čillík <notifications@github.com>:

**Comment by MiroCillik** [comment]
Hmm, este to furt nefunguje :/ Ked to vyzskuam priamo z docker workeru, zarve mi to na firewalle:

"Cannot open server 'keboola-bata' requested by the login. Client with IP address '52.91.171.173' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect."

**Comment by padak** [comment]
@MiroCillik po změně na tu verzi 8.0 to ale stejně nejede. Je to nasazené?

**Comment by MiroCillik** [comment]
@padak je to nasadene, precitaj si ten koment vyssie, hadze to teraz chybu kvoli firewallu, z docker-workeru sa mi tam nepodarilo pripojit (ani cez tsql clienta).

**Comment by MiroCillik** [comment]
@padak ahaa jasne, ty si v tom firewalle povolil len tie 2 normalne syrup-workery, ja som myslel, ze si tam dal ten syrup-out.keboola.com. Zistim ti adresy tych docker workerov.

**Comment by MiroCillik** [comment]
52.91.171.173 a 52.90.177.255.. Toto mas len na nejaky test, ze?

**Comment by padak** [comment]
aha! povolil jsem to všechno - pustil a nevalí to (https://connection.keboola.com/admin/projects/924/jobs/168159595) - je snadný mi dát příkazy, co to dělá? Že bych to celý replikoval a pomohl debugovat?

**Comment by MiroCillik** [comment]
sakra! On ten docker image na ktorom to bezi je celkom zlozity, ja sa na to pozriem.

**Comment by padak** [comment]
díky!


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by MiroCillik** [comment]
Uz som to rozchodil, vyhodil som z connection stringu port a vali to... divne.. mozes prosim overit na akom porte ti ta DB bezi?

**Comment by padak** [comment]
imho na 1433


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by MiroCillik** [comment]
nj, inak to ani nedava zmysel. Divne, lebo na tu testovaciu databazu sa to pripoji vpohode (s portom v connection stringu) ale na tuto tvoju nie. Zatial to teda osetrim tak, ze pokial je port defaultny (1433) tak ho do toho stringu davat nebudem. A uvidime.

**Comment by padak** [comment]
ok. dej vědět, až to mužu zkusit

**Comment by MiroCillik** [comment]
Vyzera, ze to funguje https://connection.keboola.com/admin/projects/924/jobs/168166711

**Comment by padak** [comment]
funguje!
