### ISSUE TITLE
MSSQL: formát dat - nejde to loadovat

### ISSUE THREAD

**Issue by padak** [keboola/db-writer-bundle#5]
Tabulka, co je na Redshiftu validní a jde v pohodě poslat do GoodData, nejde loadnout do MSSQL. 

Nejdřív to hodilo chybu
```
[2016-01-22 13:37:20] wr-db.ERROR: SQLSTATE[HY000]: General error: 20018 Unclosed quotation mark after the character string ')'. [20018] (severity 15) [] [] []
```
([writer job](https://connection.keboola.com/admin/projects/924/jobs/168171856?q=))

Tak jsem pomocí:
```
UPDATE transactions 
SET kategorie = REPLACE(kategorie,'(','');
UPDATE transactions 
SET kategorie = REPLACE(kategorie,')','');
```
([writer job](https://connection.keboola.com/admin/projects/924/jobs/168246633?q=))

provizorně smazal z dat závorky ([transformace](https://connection.keboola.com/admin/projects/924/transformations/bucket/padak/transformation/debug)). A pak když jsem to loadnul jsem dostal:

```
[2016-01-22 21:50:52] wr-db.ERROR: SQLSTATE[HY000]: General error: 20018 Incorrect syntax near 'S'. [20018] (severity 15) [] [] []
```

což už mi sebralo sílu debugovat. Potřeboval bych vidět co to do MSSQL serveru posílá za data a jak přesně to dělá.

(nehoří to hned teď)

**Comment by MiroCillik** [comment]
Pozriem na to

**Comment by Halama** [comment]
tohle staci nahlasit jako bug ex, neni treba dalsi debug ani logy. O to se postara autor...

**Comment by MiroCillik** [comment]
Vylepsil som escapovanie, s tym mssql je vsetko problematicke :( Teraz to hadze chybu ```Error converting data type varchar to numeric.``` co moze byt aj nieco taketo https://www.mssqltips.com/sqlservertip/4008/handling-error-converting-data-type-varchar-to-numeric-in-sql-server/

**Comment by padak** [comment]
díky, mrknu na to


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by MiroCillik** [comment]
Niektore stlpce som zmenil na typ NVARCHAR. To 'N' znamena, ze su v UNICODE kododovani, to je myslim dobre davat, ked je v datach diakritika a tak. 

Este sa snazim spravit aby to nejak rozumne zalogovalo tu query, ale stejne v tej query bude 3000 riadkov, tak neviem ci to moc pomoze :/

**Comment by padak** [comment]
omg! 3k řádků je peklo.

jestli je NVARCHAR to co pises, bylo by super změnit UI aby to nabízelo
někde nahoře - ten seznam je dlouhej a lopaty neví co vybrat. co myslis?


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek


2016-01-25 16:41 GMT+01:00 Miroslav Čillík <notifications@github.com>:

**Comment by MiroCillik** [comment]
JJ, nieco take, poriesim to s Kacurezom. Ja tohle nejak oddebuggujem na develi.

**Comment by padak** [comment]
teď to sype novej [typ erroru](https://connection.keboola.com/admin/projects/924/jobs/168771856?q=)

```
[2016-01-25 16:35:22] wr-db.ERROR: SQLSTATE[HY000]: General error: 20018 The number of row value 
expressions in the INSERT statement exceeds the maximum allowed number of 1000 row values.
[20018] (severity 15) [] [] []
ExceptionId docker-df854aa267ab15723911206318a11ac3
```

mám na to udělat vlastní issue? Nemusíš to řešit hned!

**Comment by MiroCillik** [comment]
Toto vyresim hned

**Comment by MiroCillik** [comment]
Som nevedel, ze limit je 1000 a zvysil som ho prave na 3k...

**Comment by MiroCillik** [comment]
Builduje sa to. Ja si zajtra tie data hodim na devel a tam to otestujem, ze s cim to ma problem vlastne. Teraz uz potrebujem bezat.

**Comment by padak** [comment]
ok, dík!


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by MiroCillik** [comment]
Problem je v tomto http://www.sqlines.com/oracle/insert_empty_string_to_numeric_column

V decimalovych poliach su prazdne hodnoty a s tym si ta DB sama neporadi. Myslim, ze by sa to malo vyriesit v "predzpracovani" (ie v transformaci). 

Ked to vo writeri nahradim "NULL", tak to funguje, ale to nemusis chciet vzdy, napriklad pri varchar poliach tam chces mat prazdny string a pod. Problem je len pri tych decimal poliach.

A teraz ako to nejak rozumne povedat uzivatelovi, kde je chyba... Funguje to tak, ze v jednej query je 1000 riadkov, aby to bolo co najrychlejsie. Ale uzivatel by trebars mohol tuto hodnotu menit, pokial by mal problemy a znizit ju trebars na 3 riadky, takze by lahsie odhalil problem.. ala devel mod - insertujem po jednom riadku, produkcny mod - insertujem po 1000

**Comment by MiroCillik** [comment]
Upravil som teda nakoniec tak, ze pri decimale sa to zachova stejne ako pri INT, vlozi tam 0 (cislo nula).

A spravim konfigurovatelny ten pocet riadkov v inserte, kvoli debugu.
